### ISSUE TITLE
Define Project Scope

### ISSUE THREAD

**Issue by larevolucia** [larevolucia/neuroconnect#1]
### Problem Statement
**Summary**: _Lack of Support for Neurodivergent Expat Community in Amsterdam_

Neurodivergent individuals (autism, ADHD, dyslexics, etc.) often face unique challenges in daily life. For expats, these challenges are exarcebated by unfamiliriarity with healthcare system, government support, language barriers and isolation from a social support network.
Despite of growing international awereness, due to significant increases in diagnoses[1], support for expats is still limited, making it difficult to find professional guidance and community support. 

### Proposed Solution
**Summary**: _A support hub for neurodivergent expats in Amsterdam_

Inclusive approach to provide support for people with different social and economical backgrounds, providing a range of professional services through certified coaches and volunteer led community support. 

### Tasks

- [x] Validate Project Problem (search statistics, social media forums)
- [x] Detail site areas and services provided (121 coaching, groups session, etc)
- [x] Identify areas of product that might need special attention due to neurodiverse target group (design, copy, etc.) 
- [x] Create User Stories

**References**
[1] `https://www.theguardian.com/society/2024/mar/04/uk-increase-autism-diagnoses-neurodiversity`

**Comment by larevolucia** [comment]
### Autism is an verlooked population

> Autistic adults are an overlooked population.  It’s assumed that those who need support can’t work and those who can work don’t need support.  
[spectroomz](https://www.spectroomz.com/blog/autism-employment-statistics#2=)
> There is a significant lack of investment in social care research.
> Many autistic people do not receive an autism diagnosis until adulthood, whilst many more don’t receive a diagnosis at all, leaving them unrecognised and unsupported. Autistic adults often report finding the process of seeking a diagnosis lengthy and difficult
[Autistica](https://www.autistica.org.uk/downloads/files/Autism-Top-10-Your-Priorities-for-Autism-Research.pdf)

### Couseling impact
> "She has parents role-play to gain perspective on what the child might be thinking or feeling and to increase awareness of behavioral patterns." This method helps parents engage with their children’s unique forms of communication and behavior​
[Counseling Today Archive - Archive](https://ctarchive.counseling.org/2020/05/supporting-families-on-their-autism-journeys/)
>To make the most of autism counseling, it is essential to establish a strong partnership between parents and counselors. This collaboration creates a supportive environment and enhances the effectiveness of the counseling process"​(
[TotalCareABA](https://www.totalcareaba.com/autism/autism-counseling)
).
>Through the use of these stories, Jay was better able to communicate which areas he needed further explained, and which areas he needed further support with

[National Autistic Society](https://www.autism.org.uk/advice-and-guidance/professional-practice/exploring-the-versatility-of-strategies-to-support)


### Importance of social groups
> 70% of autistic children have a mental health problem with 79% of autistic adults meeting criteria for a mental health problem 70% of autistic children have a mental health problem with 79% of autistic adults meeting criteria for a mental health problem 
[Autistica](https://www.autistica.org.uk/downloads/files/Autism-Top-10-Your-Priorities-for-Autism-Research.pdf)
>Research suggests that autistic people are more likely to experience feelings of loneliness compared to non-autistic people. This can be due to a lack of acceptance and understanding by society, making them feel excluded.
>Specific barriers to social opportunities include: unwelcoming sensory environments (such as noisy pubs or restaurants); social anxiety; fear of rejection; experiences of bullying; lack of formal support (in education or as an adult).
[Autism.org.uk]( https://www.autism.org.uk/advice-and-guidance/topics/loneliness#:~:text=Research%20suggests%20that%20autistic%20people,society%2C%20making%20them%20feel%20excluded.)
> A large active local group can have a real influence on the provisions and services that local government or health service providers make available.
[Special Learning](https://special-learning.com/the-importance-of-support-groups/)
> Existing employment interventions for adults with autism have leveraged social support, such as by job seekers eliciting feedback, guidance, or obtaining job-related video tips from volunteers.
[Collaborative Design for Job-Seekers with Autism: A Conceptual Framework for Future Research](https://arxiv.org/html/2405.06078v2)

### Importance of free support
> 15–20% of autistic adults are in full-time employment, but according to the National Autistic Society, 79% of autistic adults who do not work or are on benefits want to work.
> US research shows that 50% of autistic youths do not take part in employment or education in the first two years after leaving school, and that those who do work are paid substantially less than the national average.
[Autistica](https://www.autistica.org.uk/downloads/files/Autism-Top-10-Your-Priorities-for-Autism-Research.pdf)
> Data support these claims: CNBC news reports that the unemployment rate for neurodivergent individuals in the US is as high as 30% to 40% percent
[John Hopkins University] (https://imagine.jhu.edu/blog/2022/10/05/neurodivergence-at-a-glance/)

**Comment by larevolucia** [comment]
Design ticket opened to address special needs for target audience: [Accessibility for Target Group](https://github.com/larevolucia/neuroconnect/issues/3)

References:
[Digital Accessibility for Web Design for Autism](https://overlayfacts.org/blog/digital-accessibility-web-design-for-autism/)
[Make it autism friendly](https://medium.com/@oksana.iudenkova/create-an-accessible-website-make-it-autism-friendly-db6821c72ed3)
[Web Design for autism](https://www.unimelb.edu.au/accessibility/web-design-for-autism)
[Design for autism](https://www.a11y-collective.com/glossary/autism/)

**Comment by larevolucia** [comment]
Services offered were focused on the social aspect, which seems to be available for Dutch speakers, but not for expats. 121 coaching was removed. 

- Home
   - Header: image + short description
   - Short summary of the platform 
   - Short summary of services and events provided
- Services
    - Guidance for seeking diagnosis (free, volunteer)
    - Guidance regarding available government benefits (free, volunteer) 
    - Facilitated group sessions: parents, autistic teens, autistic adults (professional service)
- Events
    - Book Club
    - Nature walks 
    - Game night
    - Paralel play
