### ISSUE TITLE
Design for Target Group

### ISSUE THREAD

**Issue by larevolucia** [larevolucia/neuroconnect#3]
Neurodiverse people process information in different ways when compared with their neurotypical counterparts.

**Task**

- [x] Validate Font styles 
- [x] Validate line-height and spacing
- [x] Validate Color scheme

**Comment by larevolucia** [comment]
[Autism Accessibility Guidelines Research Final Report - HI for National Autistic Society - tagged.pdf](https://github.com/user-attachments/files/17309147/Autism.Accessibility.Guidelines.Research.Final.Report.-.HI.for.National.Autistic.Society.-.tagged.pdf)

Guidelines on design to be use for Testing and validation or project

**Comment by larevolucia** [comment]
Research showed a preference for blue and green colors in muted tons. 
Proposed Palette with color blindness test:
![Image](https://github.com/user-attachments/assets/6a9237f9-1913-4148-b867-b1500aff1990)

**Comment by larevolucia** [comment]
Font formatting recommended by [Accessibility Checker](https://www.accessibilitychecker.org/)

> Font Formatting
> Even though you may have picked a dyslexia-friendly font, paying attention to formatting can also make a difference to readability.
> - A 12-14 point type is highly recommended.
> - Character spacing should equal around 30% of the letter’s horizontal dimensions.
> - Don’t italicize or underline text if you can help it.
> - Don’t type in all caps if you can avoid it.
> - Opt for line spacing of 1.5.

**Comment by larevolucia** [comment]
[Lexend](https://www.lexend.com/) typeface is dyslexic friendly and has been validated to make reading easier.
It will be used for our body.

Research also showed that distinction of elements is important for autistic people, so we selected Roboto Slab for headings.
Although Roboto Slab is a serif typeface the serifs are subtle providing distinction without compromising readability.

**Comment by larevolucia** [comment]
![Image](https://github.com/user-attachments/assets/36c15e67-a365-4091-8ec8-398d0dfd448e)
Adjustments made to pallete for WCAG contrast
